#!/home/sirpipat/anaconda2/bin/python

'''
==============================================================================

File Name : map_SS_S_amp_rat_avg
Purpose : map SS-S amplitude ratio from h5 data_file
Creation Date : 04-02-2018
Last Modified : Mon 18 Sep 2017 04:43:24 PM EDT
Created By : Samuel M. Haugland

==============================================================================
'''

import numpy as np
from obspy.geodetics.base import gps2dist_azimuth
import geopy
from geopy.distance import VincentyDistance
from matplotlib import pyplot as plt
from mpl_toolkits.basemap import Basemap
import argparse
import h5py
from glob import glob


def main():
    parser = argparse.ArgumentParser(
                       description='map S times')
    parser.add_argument('-f','--h5_files',metavar='*picks.h5',type=str,
                        help='list of h5_files')
    parser.add_argument('-l','--max_dist',metavar='float',type=float,
                        default=180,help='maximum_distance (deg)')
    parser.add_argument('-s','--min_dist',metavar='float',type=float,
                        default=40,help='minimum distance (deg)')
    parser.add_argument('--min_c1',metavar='float',type=float,
                        default=0.5,help='minimum corcoeft_1 allowed')
    parser.add_argument('--min_c2',metavar='float',type=float,
                        default=0.75,help='minimum corcoeft_2 allowed')
    parser.add_argument('--min_lsq1',metavar='float',type=float,
                        default=0.5,help='minimum lsq_1 allowed')
    parser.add_argument('--min_lsq2',metavar='float',type=float,
                        default=0.70,help='minimum lsq_2 allowed')
    parser.add_argument('--max_dt',metavar='float',type=float,
                        default=30.0,help='maximum delta_T')
    parser.add_argument('--dt_shift',metavar='bool',type=bool,
                        default=True,help='mandate updated time shift be less\
                                           than original')

    args = parser.parse_args()
    fig,ax = plt.subplots()
    dat_list = glob(args.h5_files)
    m = Basemap(projection='mbtfpq',lon_0=180,resolution='c')
    m.drawparallels(np.arange(-90.,120.,30.))
    m.drawmeridians(np.arange(0.,360.,60.))
    m.drawcoastlines()
    s10_total = 0
    s20_total = 0
    sdiff20_total = 0

    # arrays storing data for each 20*20 degree bin
    SS_S_amp_rat_sum = np.zeros([17,36])
    SS_S_amp_rat_bin = np.zeros([17,36])

    for ii in dat_list:
        print ii
        h5f = h5py.File(ii,'r',driver='core')
        try:
            s10_total += list_plot(h5f,m,s10_total,'S10',SS_S_amp_rat_sum,
                                   SS_S_amp_rat_bin,args)
        except IndexError:
            print 's10_index'
            s10_total += 0
        try:
            s20_total += list_plot(h5f,m,s20_total,'S20',SS_S_amp_rat_sum,
                                   SS_S_amp_rat_bin,args)
        except IndexError:
            print 's20_index'
            s20_total += 0
        try:
            sdiff20_total += list_plot(h5f,m,sdiff20_total,'Sdiff20',
                                       SS_S_amp_rat_sum,SS_S_amp_rat_bin,args)
        except IndexError:
            print 'sdiff_index'
            sdiff20_total += 0
            continue

    print 'SS20-S10 total: ', s10_total
    print 'SS20-S20 total: ', s20_total
    print 'SS20-Sdiff20 total: ', sdiff20_total

    SS_S_amp_rat_avg = SS_S_amp_rat_sum/SS_S_amp_rat_bin
    print SS_S_amp_rat_avg
    for ii in range(len(SS_S_amp_rat_avg)):
        for iii in range(len(SS_S_amp_rat_avg[ii])):
            plot_coords(m,10*ii-80,10*iii-180,SS_S_amp_rat_avg[ii,iii])

    plt.tight_layout()
    plt.savefig('SS-S_amp_rat_avg.png')
    plt.show()

def list_plot(h5f,m,total,name,SS_S_amp_rat_sum,SS_S_amp_rat_bin,args):
    try:
        s_dat = h5f[name]['pick_info'][:]
        ss_dat = h5f['SS20']['pick_info'][:]
        s_name = s_dat[:,1]
        ss_name = ss_dat[:,1]

        c = np.array(list(set(s_name).intersection(set(ss_name))))
        s_mask = np.in1d(s_dat[:,1],c)
        ss_mask = np.in1d(ss_dat[:,1],c)

        slat = np.array([float(ii) for ii in s_dat[s_mask,2]])
        slon = np.array([float(ii) for ii in s_dat[s_mask,3]])
        rlat = np.array([float(ii) for ii in s_dat[s_mask,4]])
        rlon = np.array([float(ii) for ii in s_dat[s_mask,5]])
        gcarc = np.array([float(ii) for ii in s_dat[s_mask,6]])

        S_del_t = np.array([float(ii) for ii in s_dat[s_mask,11]])
        S_update_t = np.array([float(ii) for ii in s_dat[s_mask,12]])
        S_t_shift = S_del_t+S_update_t
        S_corcoeft_1 = np.array([float(ii) for ii in s_dat[s_mask,17]])
        S_corcoeft_2 = np.array([float(ii) for ii in s_dat[s_mask,18]])
        S_lsq_1 = np.array([float(ii) for ii in s_dat[s_mask,23]])
        S_lsq_2 = np.array([float(ii) for ii in s_dat[s_mask,24]])
        S_amp_rat = np.array([float(ii) for ii in s_dat[s_mask,25]])

        SS_del_t = np.array([float(ii) for ii in ss_dat[ss_mask,11]])
        SS_update_t = np.array([float(ii) for ii in ss_dat[ss_mask,12]])
        SS_t_shift = SS_del_t+SS_update_t
        SS_corcoeft_1 = np.array([float(ii) for ii in ss_dat[ss_mask,17]])
        SS_corcoeft_2 = np.array([float(ii) for ii in ss_dat[ss_mask,18]])
        SS_lsq_1 = np.array([float(ii) for ii in ss_dat[ss_mask,23]])
        SS_lsq_2 = np.array([float(ii) for ii in ss_dat[ss_mask,24]])
        SS_amp_rat = np.array([float(ii) for ii in ss_dat[ss_mask,25]])

        S_SS_rat = np.log10(S_amp_rat/SS_amp_rat)

    except KeyError,IndexError:
        return 0

    pick_count = 0
    for ii in range(len(slat)):
        if gcarc[ii] >= args.max_dist or gcarc[ii] <= args.min_dist:
            #print 'gcarc'
            continue
        if args.dt_shift:
            if np.abs(S_del_t[ii]) < np.abs(S_update_t[ii]):
                #print 'S update'
                continue
            if np.abs(SS_del_t[ii]) < np.abs(SS_update_t[ii]):
                #print 'SS update'
                continue
        if S_corcoeft_1[ii] < args.min_c1 or S_corcoeft_2[ii] < args.min_c2:
            #print 'S corcoeft'
            #print corcoeft_1[ii],corcoeft_2[ii]
            continue
        if SS_corcoeft_1[ii] < args.min_c1 or SS_corcoeft_2[ii] < args.min_c2:
            #print 'SS corcoeft'
            #print corcoeft_1[ii],corcoeft_2[ii]
            continue
        if S_lsq_1[ii] < args.min_lsq1 or S_lsq_2[ii] < args.min_lsq2:
            #print 'S lsq'
            #print lsq_1[ii],lsq_2[ii]
            continue
        if SS_lsq_1[ii] < args.min_lsq1 or SS_lsq_2[ii] < args.min_lsq2:
            #print 'SS lsq'
            #print lsq_1[ii],lsq_2[ii]
            continue
        if S_t_shift[ii] > args.max_dt:
            #print 'S_tshift'
            continue
        if SS_t_shift[ii] > args.max_dt:
            #print 'SS_tshift'
            continue
        else:
            mlat,mlon = find_coords(slat[ii],slon[ii],rlat[ii],rlon[ii])
            add_data(mlat,mlon,SS_S_amp_rat_sum,SS_S_amp_rat_bin,S_SS_rat[ii])
            pick_count += 1

    #lon,lat = m(slon[0],slat[0])
    #m.scatter(lon,lat,color='k',s=80,marker='D',rasterized=True)
    return pick_count

def find_coords(slat,slon,rlat,rlon):
    bearing = gps2dist_azimuth(slat,slon,rlat,rlon)[1]
    dist = gps2dist_azimuth(slat,slon,rlat,rlon)[0]/2000.
    origin = geopy.Point(slat,slon)
    destination = VincentyDistance(kilometers=dist).destination(origin,bearing)
    return (destination[0],destination[1])

def add_data(mlat,mlon,SS_S_amp_rat_sum,SS_S_amp_rat_bin,S_SS_rat):
    a = int((mlat+90)/10)
    b = int((mlon+180)/10)
    if b >= 0 and b < 36:
        if a >= 0 and a < 17:
            SS_S_amp_rat_sum[a,b-1:b+1] += S_SS_rat
            SS_S_amp_rat_bin[a,b-1:b+1] += 1
        if a >= 1 and a < 18:
            SS_S_amp_rat_sum[a-1,b-1:b+1] += S_SS_rat
            SS_S_amp_rat_bin[a-1,b-1:b+1] += 1

def plot_coords(m,mlat,mlon,S_SS_rat):
    if abs(S_SS_rat) <= np.log10(1.25):
        size = 10
    elif np.log10(1.25) < abs(S_SS_rat) and abs(S_SS_rat) <= np.log10(1.5):
        size = 20
    elif np.log10(1.5) < abs(S_SS_rat) and abs(S_SS_rat) <= np.log10(2):
        size = 30
    elif np.log10(2) < abs(S_SS_rat) and abs(S_SS_rat) <= np.log10(3):
        size = 40
    elif np.log10(3) < abs(S_SS_rat) and abs(S_SS_rat) <= np.log10(5):
        size = 50
    elif np.log10(5) < abs(S_SS_rat) and abs(S_SS_rat) <= np.log10(10):
        size = 60
    elif abs(S_SS_rat) > np.log10(10):
        size = 70
    else:
        size = 5

    if S_SS_rat <= 0:
        color = 'blue'
        marker = 'o'
        facecolor='none'
    elif S_SS_rat > 0:
        color = 'red'
        marker = 'x'
        facecolor='red'
    else:
        color = 'black'
        marker = 's'
        facecolor = 'black'

    lon,lat = m(mlon,mlat)
    m.scatter(lon,lat,linewidth=1,color=color,alpha=1,
              s=5*size,marker=marker,facecolor=facecolor,rasterized=True)

main()
